# Generated by Django 4.2.5 on 2023-09-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="uesr",
            new_name="user",
        ),
    ]
