# Generated by Django 4.2.5 on 2023-10-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="discounted_price",
            new_name="present_price",
        ),
    ]
