# Generated by Django 4.2.5 on 2023-10-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_discounted_price_product_present_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="car_name",
        ),
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.CharField(default="Car", max_length=100),
        ),
    ]
