# Generated by Django 4.2.5 on 2023-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_title_product_car_name_product_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="company",
        ),
        migrations.RemoveField(
            model_name="product",
            name="composition",
        ),
        migrations.AddField(
            model_name="product",
            name="fuel_type",
            field=models.CharField(
                choices=[("petrol", "petrol"), ("Diesel", "Diesel"), ("CNG", "CNG")],
                default="petrol",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="kms_driven",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_type",
            field=models.CharField(
                choices=[("Dealer", "Dealer"), ("Individual", "individual")],
                default="indivisual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="year",
            field=models.TextField(default="1996"),
        ),
    ]
