# Generated by Django 4.2.5 on 2023-10-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_product_company_remove_product_composition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="fuel_type",
            field=models.CharField(
                choices=[("Petrol", "Petrol"), ("Diesel", "Diesel"), ("CNG", "CNG")],
                default="Petrol",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller_type",
            field=models.CharField(
                choices=[("Dealer", "Dealer"), ("Individual", "Individual")],
                default="Indivisual",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                default="Manual",
                max_length=10,
            ),
        ),
    ]
