# Generated by Django 4.2.5 on 2023-10-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_product_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderplaced",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="orderplaced",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="orderplaced",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderplaced",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AlterField(
            model_name="product",
            name="fuel_type",
            field=models.CharField(
                choices=[("Petrol", "Petrol"), ("Diesel", "Diesel"), ("CNG", "CNG")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller_type",
            field=models.CharField(
                choices=[("Dealer", "Dealer"), ("Individual", "Individual")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="OrderPlaced",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
