# Generated by Django 4.2.5 on 2023-10-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_orderplaced_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    ("Hatchback", "Hatchback"),
                    ("Sedan", "Sedan"),
                    ("MUV", "MUV"),
                    ("Luxury", "Luxury"),
                ],
                max_length=10,
            ),
        ),
    ]
