# Generated by Django 4.2.5 on 2023-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brand",
            new_name="car_brand",
        ),
        migrations.AddField(
            model_name="product",
            name="car_model",
            field=models.CharField(default="model", max_length=100),
        ),
    ]
