# Generated by Django 4.2.5 on 2023-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_rename_brand_product_car_brand_product_car_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image_front",
            field=models.ImageField(default=0, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image_left",
            field=models.ImageField(default=0, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image_rear",
            field=models.ImageField(default=0, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image_right",
            field=models.ImageField(default=0, upload_to="product"),
        ),
    ]
