# Generated by Django 4.2.5 on 2023-10-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_product_product_image_front_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_image_front",
            new_name="product_image1",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_image_left",
            new_name="product_image2",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_image_rear",
            new_name="product_image3",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_image_right",
            new_name="product_image4",
        ),
        migrations.AddField(
            model_name="product",
            name="product_image5",
            field=models.ImageField(default=0, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image6",
            field=models.ImageField(default=0, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image7",
            field=models.ImageField(default=0, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image8",
            field=models.ImageField(default=0, upload_to="product"),
        ),
    ]
